apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: terraform-provider-rhcs
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/ebelarte-tenant/terraform-provider-rhcs/terraform-provider-rhcs@sha256:deade69cdee8fdd82495bf7a5a52924b4a892531c07cc27620fe080a6bcc884d
        name: my-go
        resources: {}
status: {}
