apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: terraform-provider-rhcs
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/ebelarte-tenant/terraform-provider-rhcs/terraform-provider-rhcs@sha256:fa6c6e41790075ef482a4815b2127ca05f2d5bdffe9b7eef0a6fe9d52066f299
        name: my-go
        resources: {}
status: {}
