apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: terraform-provider-rhcs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: terraform-provider-rhcs
    app.kubernetes.io/part-of: terraform-provider-rhcs
  name: terraform-provider-rhcs
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: go-app
      app.kubernetes.io/instance: terraform-provider-rhcs
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-app
        app.kubernetes.io/instance: terraform-provider-rhcs
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/ebelarte-tenant/terraform-provider-rhcs/terraform-provider-rhcs@sha256:7d824db6f5bc778f9bc85520258e8edab13ef4894c6383292c99a33d59edbdbc
        name: my-go
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
status: {}
